min_version = { soft = "2025.12.12" }

[settings]
experimental = true
jobs = 2

[env]
RUBY_CONFIGURE_OPTS = "--enable-install-doc"
RUBY_MAKE_OPTS = "-j2"

[tool_alias]
jupyter = "pipx:jupyter[pipx_args=--include-deps --preinstall pynvim]"
mercurial = "pipx:mercurial[pipx_args=--preinstall hg-evolve --preinstall hg-git]"
